### ISSUE TITLE
Set up Dev Environments

### ISSUE THREAD

**Issue by m-gurung11** [Logic-Legends/Decision-Making-Frmwk#10]
We need
-  feature branches ✅ 
- develop branch for integration testing ✅ 
- main branch for releasing✅

**Comment by andrewwhitehouse** [comment]
@leilafaez @Ekremteke @luan-murilo-de-oliveira-e-souza @m-gurung11 do we understand what this looks like yet?

I am assuming:
- feature branches
- develop branch for integration testing
- main branch for releasing

What other details do we need in the description?

How many instances of Wordpress do we need?

It may be useful to set up a Github action which blocks merging if any tests fail. But we need some initial code to exercise.

**Comment by leilafaez** [comment]
we fork the repository

**Comment by andrewwhitehouse** [comment]
Let's split out Wordpress and Github actions to separate tickets.

**Comment by m-gurung11** [comment]
All devs have feature branch, dev branch and main branch
