### ISSUE TITLE
Define Goal

### ISSUE THREAD

**Issue by m-gurung11** [Logic-Legends/Decision-Making-Frmwk#11]
As a user I want to define the goals for the decision so that I have clarity on the agreed main objectives of the activity. 

### **Acceptance Criteria**

**Scenario 1 - Content**
GIVEN I am using the Decision Making Framework
WHEN I am on the first screen (Define Goal)
THEN I should see the header text as 'What is the goal?'
AND there should be an info icon next to the question text
AND I should see the hint text below the header text as 'Defining the goal will help you determine what kind of information you need to make a decision'

**Scenario 2 - Input field**
GIVEN I am using the Decision Making Framework
WHEN I am on the first screen
THEN I should see an input text field below the hint text
AND it should alphanumeric characters up to 500 characters

**Scenario 3 - Info tooltip**
GIVEN I am on the Define Goal screen
WHEN I hover on the info icon
THEN I should see a tooltip
AND the content should be as per note 1
AND there should be a close (X) icon on the top right

**Note 1**
What decision are we trying to make?

SMART Goals
Specific
Measurable
Achievable
Realistic
Time-based

**Scenario 3a - Close tool tip**
GIVEN the tooltip is open
WHEN I click on close (X)
THEN the tooltip should disappear

**Scenario 4 - Continue to next screen**
GIVEN I am on the Define Goal screen
WHEN I have entered a value on the input text field
AND I click 'Continue'
THEN I should be directed to the 'Who are the decision makers?' screen

**Scenario 5 - Error messaging**
GIVEN I am on the Define Goal screen
WHEN I have not entered any value on the input text field
AND I click 'Continue'
THEN I should see an error message, 'Please define your goals before you continue'

**Scenario 6 - URL**
GIVEN I am on the Define Goal screen
WHEN I check the URL
THEN it should be http://localhost:3000/define-goal

**Comment by luan-murilo-de-oliveira-e-souza** [comment]
all scenarios were followed for creating the web page

**Comment by mhallaq** [comment]
I have tested this user story. It's working as in the AC , and displaying the information when clicking the tool tip.
Furthermore I have checked all scenarios from 1 to 6 and it passes all of them.
