### ISSUE TITLE
Create User Personas

### ISSUE THREAD

**Issue by m-gurung11** [Logic-Legends/Decision-Making-Frmwk#12]
Create user personas to represent  the groups of users we are building this functionality for. You can find various templates online. It can be a fairly simple representation. 

We can start with two:

> **Researchers** (from various organisations specifically looking for tools like the DMF) and 
> **General User** (anyone who uses/vists the ACE website)

We can validate the characteristics of the personas with Ellen and Rana.

**Comment by m-gurung11** [comment]
@mhallaq @leilafaez @Ekremteke @luan-murilo-de-oliveira-e-souza please feel free to have this ticket assigned to either one or two of you only but please make sure that whoever has worked on it shares it with the rest of the group.

**Comment by m-gurung11** [comment]
Hi team, has there been any progress on this?

**Comment by leilafaez** [comment]
Hi Milan. Ekrem and I working on it

**Comment by m-gurung11** [comment]
Brilliant, thanks @leilafaez & @Ekremteke

**Comment by leilafaez** [comment]
we make 2 user personas one for Rana another, as a user . I will attach them here

![Image](https://user-images.githubusercontent.com/79403281/224778288-9423853e-3ff5-47b3-907b-f1bad1f64075.PNG)
![Image](https://user-images.githubusercontent.com/79403281/224778289-7a68d71f-9d12-48c6-9bd1-f032d15de0c3.PNG)

**Comment by m-gurung11** [comment]
Thank you @leilafaez , looks great. I have a few comments to make some revisions but we can close this task as the first draft done.
