### ISSUE TITLE
Identify deployment approach

### ISSUE THREAD

**Issue by andrewwhitehouse** [Logic-Legends/Decision-Making-Frmwk#17]

**Comment by andrewwhitehouse** [comment]
CYF currently favour using render.com for application deployment since Heroku started charging for the basic tier in November 2022.

The actual application requirements are not yet fully clear. But we can start with a simple application and build on that. 

Setup of render.com seems straightforward; connect a repository branch to a deployment with -- at least -- a staging and production site.

Render supports hooks to run tests before deployment: https://community.render.com/t/how-to-use-gitlab-ci-yml-to-execute-tests-prior-to-render-deployment/685

So this seems to meet our needs for now.

Questions still to answer:

- do we _need_ a server-side component? We may be able to deploy a static site, depending on features used, but for now let's assume a simple Node server.
- if we generate PDFs, or capture emails, there is a question of whether to do that client-side or server-side

**Comment by andrewwhitehouse** [comment]
Possible approaches for PDF generation https://dev.to/handdot/generate-a-pdf-in-js-summary-and-comparison-of-libraries-3k0p

**Comment by mhallaq** [comment]
Do we need a test repository and a test server provided by the charity to test the integration of the deployed application with their website?

**Comment by andrewwhitehouse** [comment]
Marking as blocked until we have a better view on how the application looks
