### ISSUE TITLE
Start Page

### ISSUE THREAD

**Issue by m-gurung11** [Logic-Legends/Decision-Making-Frmwk#20]
As a user I want to understand the purpose of the tool so I know what outcome to expect as a result of using it.

**Acceptance Criteria**

**Scenario 1 - Content**
GIVEN I am using the Decision Making Framework
WHEN I am on the Start screen
THEN I should see the content as per Note 1

**Note 1**

### Voting Methods for Group Decisions

This tool is designed to help facilitate group decisions that involve voting.
- 	It is for teams of 2 or more people.

**Who should complete this tool?**
1 or 2 people with good project knowledge such as the Project Manager or Team Lead.

**What is the outcome?**
You will receive a recommendation of the type of voting method to use in your group decision

**How much time will I/we need?**
We advise you spend up to 30 minutes in using the tool.

**Scenario 2 - Start button**
GIVEN I am using the Decision Making Framework
WHEN I am on the Start screen
THEN I should see a 'START' button on the bottom of the screen

**Scenario 3 - Click Start button**
GIVEN I am on the Start screen
WHEN I click on the START button
THEN I should be directed to the Define Goal screen

**Scenario 4 - URL**
GIVEN I am on the Start screen
WHEN I check the URL
THEN it should be https://starter-kit-snzl.onrender.com/

**Comment by andrewwhitehouse** [comment]
When directing to the Defined Goal screen, since this may not exist yet we can add a placeholder.
Do we need ACE style guidelines yet, and if so can we attach ACE style guidelines?
We can add tests for the acceptance criteria scenarios.

**Comment by m-gurung11** [comment]
@andrewwhitehouse Rana has said that so long as we use neutral colours it is fine since they are just about do an overall rebranding. They want to be able to adapt their new designs easily to what we build so lets stick with the same font and Rana's request of questions inside grey borders on a white background.

**Comment by andrewwhitehouse** [comment]
@Ekremteke You may need to merge/rebase your code from the development branch. Also can you add instructions on how to run it. There is plenty of opportunity to simplify this code and remove unnecessary dependencies.

**Comment by andrewwhitehouse** [comment]
@Ekremteke good job! 

A few observations:
- check the copy: "to help facilities group decision" (should be plural)
- should there be any padding around the text?
- there seem to be some issues with the button rendeing
- we need to clarify what the URL should be; generally I'd suggest that they are lower case and words are separated by hyphens

It would be great if we can add one or two automated tests, such as for the transition when clicking the button. But we don't want these to block progress, and we can circle back and add these later.

**Comment by Ekremteke** [comment]
- check the copy: "to help facilities group decision" (should be plural)
      
   fixed

- there seem to be some issues with the button rendering

   fixed

- we need to clarify what the URL should be; generally I'd suggest that they are lowercase and words are separated by hyphens

   This is the first page, for this reason, I prefer "http://localhost:3000/" as the path. But I can change.

**Comment by m-gurung11** [comment]
@Ekremteke Hi Ekrem

- I have changed the URL on the AC

**Comment by Ekremteke** [comment]
@m-gurung11 We have changed again as deployment link :)

**Comment by luan-murilo-de-oliveira-e-souza** [comment]
The page meets the acceptance criteria

**Comment by m-gurung11** [comment]
@Ekremteke , quick one from me. Please could you do an indented at the same level as the remaining text

**Comment by mhallaq** [comment]
I have tested the screen different scenarios , it works fine and pass the values to the next step.
