### ISSUE TITLE
Decision Making Capacity

### ISSUE THREAD

**Issue by m-gurung11** [Logic-Legends/Decision-Making-Frmwk#22]
As a user I want to specify how important the decision is so I can understand how it affects the type of voting method I should choose

**ACCEPTANCE CRITERA**

**Scenario 1 - Content**
GIVEN I am using the Decision Making Framework
WHEN I am on the Decision Capacity screen
THEN I should see the title text 'Capacity'
AND I should see the question text below it as 'What is the decision making team's capacity?' with an info icon

**Scenario 2 - Responses**
GIVEN I am using the Decision Making Framework
WHEN I am on the Decision Capacity screen
THEN I should see 2 radio buttons below the question text
AND I should the options as 'Low' and 'High'

**Scenario 3 - Info tooltip**
GIVEN I am on the Decision Capacity screen
WHEN I hover on the info tooltip
THEN I should see a pop-up
AND I should see the text 'Capacity = how much time decision-makers can allocate to the decision-making process"

**Scenario 3a - Close tooltip**
GIVEN the tooltip is open
WHEN I click/tap close(X) 
THEN the tooltip should disappear

**Scenario 4 - Continue**
GIVEN I am on the Decision Capacity screen
WHEN I have selected a response
AND I click Continue
THEN I should be directed to the Time and Resource Allocation screen

**Scenario 5 - Back**
GIVEN I am on the Decision Capacity screen
WHEN I click on the Back button
THEN I should be directed to the Decision Importance screen
AND the input I previously entered should be displayed

**Scenario 6 - Error Messaging**
GIVEN I am on the Decision Capacity screen
WHEN I have not selected either option
AND I click Continue
THEN I should see an error message, 'Please select a response'

**Scenario 7 - URL**
GIVEN I am on the Decision Capacity screen
WHEN I check the URL
THEN it should be https://domain/capacity

**Comment by leilafaez** [comment]
I fix the tooltips by following step1 desing for capacity page
I save the user selection on radio btn on local storage 
all acceptance critrias have covered

**Comment by mhallaq** [comment]
Nice work Leila, I have noticed that sometime the form can proceed to the next step even the user did not select any option.

**Comment by leilafaez** [comment]
I didn't see this issue when I test it.

**Comment by mhallaq** [comment]
I have tested the screen different scenarios , it works fine and pass the values to the next step.
