### ISSUE TITLE
Time and Resource Allocation

### ISSUE THREAD

**Issue by m-gurung11** [Logic-Legends/Decision-Making-Frmwk#23]
As a user I want to know how I should allocate time and resources to the group decision so we can be effective in our approach

**Scenario 1 - Content**
GIVEN I am using the Decision Making Framework
WHEN I am on the Time and Resource Allocation screen
THEN I should see header text 'Time and Resource Allocation' with an info icon
AND I should see the text below as per Note 1

**Note 1**
Please look up the content based on user's selections on Decision Importance and Capacity screens
Importance | Capacity | Content
-- | -- | --
High | High | High Importance and High Capacity Advice: Allocate as much time as you can to gather information and make a good decision. You could use a more complex voting method
High | Low | High Importance and Low Capacity Advice: Start sooner, de-prioritize other tasks that are taking up capacity, or use a less complex voting method that requires less information
Low | High | Low Importance and High Capacity Advice: Start the decision- making process later, take more time to gather information, or use a more complex voting method
Low | Low | Low Importance and Low Capacity Advice: Choose a single iteration, low complexity voting method. Don't spend too much time gathering information

**Scenario 2 - Info tooltip**
GIVEN I am on the Time and Resource Allocation screen
WHEN I click/hover on the info icon
THEN I should see a tooltip with text 'Spending more time on decisions creates an opportunity to gather and use more information, leading to higher specificity and detail in the voting method.'
AND I should see a close(X) icon on the top right

**Scenario 2a - Close tooltip**
GIVEN the tooltip is open
WHEN I click on close(X)
THEN the tooltip should disappear

**Scenario 3 - Continue**
GIVEN I am on the Time and Resource Allocation screen
WHEN I click on Continue
THEN I should be directed to Nature of Decision

**Scenario 4 - Back**
GIVEN I am on the Time and Resource Allocation screen
WHEN I click on Back
THEN I should be directed to Decision Making Capacity

**Scenario 5 - URL**
GIVEN I am on the Time and Resource Allocation screen
WHEN I check the URL
THEN it should be http://localhost:3000/time-resource

**Comment by luan-murilo-de-oliveira-e-souza** [comment]
I performed page connectivity using useLocation() to send information

**Comment by mhallaq** [comment]
I have tested this user story. It's working as in the AC , and displaying the information according to the selected options of the Capacity and Importance on the previous step.Furthermore I have checked all scenarios from 1 to 5 and it passes all of them.
