### ISSUE TITLE
Create a Figma prototype - V1

### ISSUE THREAD

**Issue by m-gurung11** [Logic-Legends/Decision-Making-Frmwk#25]
Create a Figma prototype to demo to client as well as use in usability testing with users.

**Comment by m-gurung11** [comment]
V1 was created and shown to clients of Friday 10/03 and tested with a user on 12/03.

**Comment by luan-murilo-de-oliveira-e-souza** [comment]
I developed the design requested by Rana for the user journey in Figma, after some meetings with Rana, some criteria for the design were established and the user journey was updated and sent to Rana for feedback. Here is the [link](https://www.figma.com/proto/9rJSROPIeYhrtHArqIPWwp/Decision-Making-Framework-Luan?node-id=243-173&starting-point-node-id=243%3A173)
