### ISSUE TITLE
Create the initial user journey

### ISSUE THREAD

**Issue by m-gurung11** [Logic-Legends/Decision-Making-Frmwk#4]
We need to create a user journey shaped by our thoughts, impressions and ideas of the decision making framework as it is currently. This will help us present our ideas to Ellen and Rana, and we can then modify our thoughts based on additional information they provide us with.

Here is the Figma file the team is working on: https://www.figma.com/file/uKwspmJNZJVxQFWogPY0Wx/Decision-Making-Framework?node-id=0%3A1&t=PGxBHUKG4joUmDVf-0

Activity can be marked done once presented to Ellen/Rana and feedback taken. We will create another task to refine the user journey and get sign-off on designs.

**Comment by luan-murilo-de-oliveira-e-souza** [comment]
Each person on the team selected a step to develop in the user journey, I chose step number 2 and it was done on Figma. I added the link of user journey on Figma at top of channel nw5-logic-legends on slack.

**Comment by m-gurung11** [comment]
@luan-murilo-de-oliveira-e-souza looks great Luan, I'm really liking the design choices you have made 🔥

**Comment by mhallaq** [comment]
Hey All , 

I have done step 1 and step 6 as agreed with the whole team. And you can find the protoype [here ](https://www.figma.com/proto/uKwspmJNZJVxQFWogPY0Wx/Decision-Making-Framework?page-id=0%3A1&node-id=28%3A184&viewport=616%2C-332%2C0.5&scaling=scale-down&starting-point-node-id=28%3A184)in this link. I would appreciate if you have a time to post your feedback here .

**Comment by m-gurung11** [comment]
@mhallaq thank you Mohammed, looks great 🔥 I have included the Figma link at the top on ticket description

**Comment by m-gurung11** [comment]
@leilafaez brilliant🔥  , thanks Leila. Please can I ask you to create 3 more screens to show the variations of importance vs capacity responses. Please could you also show on the second screen what hint text would be displayed if they hovered on importance and on the third screen what hint text would be displayed if they hovered on capacity. Or you could simply have those appear as hint text below each questions.

**Comment by Ekremteke** [comment]
My parts were steps 5 and 7. I have done them.

**Comment by m-gurung11** [comment]
@Ekremteke thanks Ekrem, fab job🔥. Please can I ask you to make this consideration: For Step 7, please can you create two outcomes. One where the user is displayed with the Explicit Values table if they have selected explicit values and another where the user is displayed with Relative Values table if they have selected Relative values.

**Comment by Ekremteke** [comment]
Thank you Milan I added question text and created one more 7th-step page to separate explicit and relative values.

**Comment by leilafaez** [comment]
@m-gurung11 unfortunatley it is my first time working with Figma so I was not familiar enough with the dashbord to design sufficiently. I tried to add tooltips and another section of step 4 as well. If there are comments to improve it please let me know.

**Comment by m-gurung11** [comment]
Hi @leilafaez , it looks like on the left hand side if you click on the step you're trying to duplicate, i.e. Step 3-1 in this case, then you can right click and select copy and do a paste on the board so it duplicates the screen. Then you can change the selection. I have done Step 3-2, could you try 3-3 and 3-4?

**Comment by leilafaez** [comment]
@m-gurung11 I think it is better to have 1 page for step 3 with a sample of tooltip for 2 instance of information for the Capacity and importance question and then go to step 4-1 with tooltip and content .... Is that correct? I cannot understand what should I put on 3-3 or 3-4?

**Comment by m-gurung11** [comment]
@leilafaez Hi Leila, for Step 3-3 and 3-4 you show the remaining combinations, i.e. User has selected high importance and low capacity and user has selected high importance and high capacity. I agree that we only need 1 page to show the sample tooltip so you dont need to replicate it on 3-2, 3-3 and 3-4

**Comment by m-gurung11** [comment]
Created and presented to ACE stakeholders. Luan will be sending email to ask for feedback. Well done team @leilafaez , @mhallaq , @luan-murilo-de-oliveira-e-souza  and @Ekremteke 👏🏼👏🏼👏🏼

**Comment by luan-murilo-de-oliveira-e-souza** [comment]
I developed the design requested by Rana for the user journey in Figma, after some meetings with Rana, some criteria for the design were established and the user journey was updated and sent to Rana for feedback. Here is the [link](https://www.figma.com/proto/9rJSROPIeYhrtHArqIPWwp/Decision-Making-Framework-Luan?node-id=243-173&starting-point-node-id=243%3A173)
