### ISSUE TITLE
Present back progress from first sprint

### ISSUE THREAD

**Issue by m-gurung11** [Logic-Legends/Decision-Making-Frmwk#5]
This is the first Show and Tell you will be doing with the rest of the class so please create a presentation which outlines the following:

1. Initial meeting with PM (Milan) and Tech Lead (Andrew)
2. Ways of Working
3. Project Workflow
4. Initial meeting with PO (Rana)
5. Initial meeting with Ellen (Researcher at ACE, Creator of framework) and an initial view of the user journey

**Comment by leilafaez** [comment]
I create a templete for the presentation and share it
design slides as a scenario that happened in our first sprint
I will present slide 9 -10 that will navigated from slide 4
we should talk about 1min for each person
here is the [link](https://docs.google.com/presentation/d/1eBTiARXnRkwQrzQqR1UJoeuZIu4ITKtD269QwKBW5RM/edit?usp=sharing)

**Comment by m-gurung11** [comment]
@leilafaez looks amazing, thanks Leila and team. I have made some tiny changes. Look forward to you all presenting tomorrow.

**Comment by m-gurung11** [comment]
Brilliant job on this team, well done 👏

**Comment by luan-murilo-de-oliveira-e-souza** [comment]
Leila and I created the presentation of the first sprint, where we presented all the steps developed in the first sprint, I presented slides 5 and 6. Here is the [link](https://docs.google.com/presentation/d/1eBTiARXnRkwQrzQqR1UJoeuZIu4ITKtD269QwKBW5RM/edit#slide=id.g2190c8c7bf2_0_850) to the presentation
