### ISSUE TITLE
Recommended Voting Method

### ISSUE THREAD

**Issue by m-gurung11** [Logic-Legends/Decision-Making-Frmwk#63]
As a user I want to be presented with a suggested voting method/s so I can use it in my decision making

**Scenario 1 - Content**
GIVEN I am using the Decision Making framework
WHEN I am on the Recommended Voting Method screen
THEN I should see the title Recommended Voting Method
And see content as per this table: https://docs.google.com/spreadsheets/d/1X6HUFnAOyaBbzSsXCqMVvP1-qO7KUlbJTJmIewFfUcg/edit?usp=sharing
AND below the voting method I should see 'To consult the full voting method use this link'

**Scenario 2 - Multiple options**
GIVEN I have selected Relative info on Step 6
WHEN I am on the Recommended Voting Method screen
THEN I should be presented with both options separated by an OR
AND I should be able to select one option

**Scenario 3 - Select option and Continue**
GIVEN I am presented with selecting options 
WHEN I select an option
AND I click Continue
THEN I should be directed to the Results screen

**Scenario 3a - Continue**
GIVEN I am not required to select an option
WHEN I click Continue
THEN I should be directed to the Results screen

**Scenario 4 - Back**
GIVEN I am on the Recommended Voting Method screen
WHEN I click Back
THEN I should be direct to the Amount of Information screen

**Scenario 5 - Full Voting Table**
GIVEN I am on the Recommended Voting Method screen
WHEN click on the link
THEN it should open a separate screen with the full voting methods table

**Scenario 6 - URL**
GIVEN I am on the Recommended Voting Method screen
WHEN I check the URL
THEN I should see http://localhost:3000/voting-method

**Comment by mhallaq** [comment]
I have tested the screen different scenarios , it works fine and pass the values to the next step.
