### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by m-gurung11** [Logic-Legends/Decision-Making-Frmwk#67]
As a user I want to see a compilation of all of my responses so I can recall the information I entered across the 7 Steps and get a copy of it.

**Scenario 1 - Content**
GIVEN I am using the Decision Making Framework
WHEN I am on the Result page
THEN I should see the content as per Note 1
AND there should be a Generate PDF button on the bottom

### You have completed the tool. Please check your responses below.

**(Info)You can click on individual steps in the progress bar to go back and change any of the responses.**

Voting Method | Value from Step 7
-- | --
What | Value from Step 1
Who | Value from Step 2
Importance | Value from Step 3a
Capacity | Value from Step 3b
Time and Resource | Value from Step 4
Type of Decision | Value from Step 5
Type of Information | Value from Step 6a
Amount of Information | Value from Step 6b

**Scenario 2 - Generate PDF**
GIVEN I am on the Results page
WHEN I click the Generate PDF button
THEN I should get a download of a 2 page PDF with the results 
AND the first page should have responses from the tool
AND the second page should have the full voting methods table

**Scenario 3 - URL**
GIVEN I am on the Results page
WHEN I check the URL
THEN I should see http://localhost:3000/results

**Comment by leilafaez** [comment]
@m-gurung11 for time and resource row in the above table what should be the value? it is step 4 which the result of step 3a and 3b

**Comment by m-gurung11** [comment]
@leilafaez yup it should have the advice from time and resource step

**Comment by leilafaez** [comment]
@luan-murilo-de-oliveira-e-souza could you please make a context variable for step 4 that I can use it in the result?
